package subway.domain;

import org.springframework.lang.NonNull;

import javax.persistence.*;
import java.util.Objects;


/*
create table station (
       id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (id)
)
 */
@Table(name = "station")
@Entity
public class Station {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // auto_increment 를 사용해라
    private Long id;

    // @NonNull
    @Column(nullable = false)
    private String name;

    @ManyToOne
    @JoinColumn(name = "line_id")
    private Line line;

    public Station() { //jpa 가 사용하는 기술과 관련, 조회를 해올때 빈 생성자를 이용해서 instance 를 생성해서 값들을 채워나간다.
    }

    public Station(String name) {
        this(null, name);
    }

    public Station(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    public void setLine(Line line) {
        if (Objects.nonNull(this.line)) {
            this.line.getStations().remove(this);
        }
        this.line = line;
        line.getStations().add(this);
    }

    public Line getLine() {
        return line;
    }

    public Long getId() {
        return this.id;
    }

    public String getName() {
        return this.name;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Station station = (Station) o;
        return Objects.equals(id, station.id) && Objects.equals(name, station.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name);
    }

    public void changeName(String name) {
        this.name = name;
    }
}
